[workspace]

members = [
  "lan-play",
  "rawsock",
]

# [patch.'https://github.com/switch-lan-play/smoltcp.git'.smoltcp]
# path = '../smoltcp'

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
panic = "abort"
