[package]
name = "lan-play"
version = "0.1.0"
authors = ["spacemeowx2 <spacemeowx2@gmail.com>"]
edition = "2018"

[dependencies]
rawsock = "0.2.0"

[dependencies.smoltcp]
version = "0.5.0"
default-features = false
features = [
    "std", "log",
    "proto-ipv4",
    "socket-raw", "socket-tcp", "socket-udp", "socket-icmp"
]
