[package]
name = "lan-play"
version = "0.1.0"
authors = ["spacemeowx2 <spacemeowx2@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "0.1"

[dependencies.rawsock]
git = "https://github.com/spacemeowx2/rust-rawsock.git"
branch = "workaround-macos"

[dependencies.smoltcp]
version = "0.5.0"
default-features = false
features = [
    "std", "log",
    "proto-ipv4",
    "socket-tcp", "socket-udp", "socket-icmp"
]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }
