[workspace]

members = [
  "lan-play",
  "rawsock",
]

# [patch.'https://github.com/switch-lan-play/smoltcp.git'.smoltcp]
# path = '../smoltcp'

[profile.release]
opt-level = 'z'
lto = "thin"
codegen-units = 1
panic = 'abort'
