[package]
name = "lan-play"
version = "0.1.0"
authors = ["spacemeowx2 <spacemeowx2@gmail.com>"]
edition = "2018"

[dependencies]
tokio = "0.2"
rawsock = "0.2.1"
crossbeam-utils = "0.6"
env_logger = "0.4"
log = "0.4"
hyper = "0.12"
futures-preview = "=0.3.0-alpha.17"
mio = "0.6"

[dependencies.smoltcp]
# version = "0.5.0"
git = "https://github.com/switch-lan-play/smoltcp.git"
branch = "accept-all-v0.5.0"
default-features = false
features = [
    "std", "log",
    "proto-ipv4", "proto-ipv6",
    "socket-tcp", "socket-udp", "socket-icmp",
    "verbose",
    "socket-accept-all", "arp-fake-subnet"
]

[patch.crates-io.rawsock]
git = "https://github.com/szymonwieloch/rust-rawsock.git"
branch = "master"
# git = "https://github.com/spacemeowx2/rust-rawsock.git"
# branch = "loop_infinite-dynamic"
# path = '../rust-rawsock'

# [patch.'https://github.com/switch-lan-play/smoltcp.git'.smoltcp]
# path = '../smoltcp'


[patch.crates-io.tokio]
git = "https://github.com/tokio-rs/tokio"
branch = "master"

[target.'cfg(windows)'.dependencies]
libc = "0.2"

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
nix = "0.14"

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
panic = "abort"
